### ISSUE TITLE
Localhost unable to connect to database on fresh clone

### ISSUE THREAD

**Issue by ianfromdover** [modtree/modtree#125]
**Describe the bug**
Cannot connect to PostgreSQL on port 5432

**To Reproduce**
1. Install all build prerequisites using HomeBrew (Node, Yarn and PostgreSQL)
2. follow the [quick start guide](https://modtree-docs.vercel.app/docs/developer-guide/build#build-prerequisites) from step 1-5

**Expected behavior**
On opening `http://localhost:3000` in the browser, I should be able to search for more modules.

**Actual behavior**
I am unable to search for more modules other than those displayed in the screenshot.

**Screenshots**
Only limited to the modules I started with
![Screenshot 2022-06-02 at 9 34 48 PM](https://user-images.githubusercontent.com/62384984/171641517-462dac69-147f-4185-bc6b-9a415218905a.png)

Connection refused by postgres
![Screenshot 2022-06-02 at 9 16 11 PM](https://user-images.githubusercontent.com/62384984/171639724-351d189c-92f4-4793-bcae-617a5ab8e013.png)

`psql` returns this message
![Screenshot 2022-06-02 at 9 53 11 PM](https://user-images.githubusercontent.com/62384984/171645280-4813bffc-b0b6-43ca-bedc-cd4b0668d9e3.png)

on running `postgres -D /usr/local/var/postgres/` it gives the error

```bash
2022-06-02 22:04:05.592 +08 [44113] FATAL:  database "modtree" does not exist
```

and a different error is shown when running `yarn dev`
![Screenshot 2022-06-02 at 10 05 33 PM](https://user-images.githubusercontent.com/62384984/171647784-da053b34-ce4e-46de-9cbd-fa9a2cdfa342.png)

**Desktop:**
 - OS: macOS Catalina 10.15.7
 - Browser: Safari 15.4 (default), have Chrome too
 - Node v16.13.1, Yarn v1.22.19, PostgreSQL v14.3, all installed using HomeBrew

**Additional context**
I just installed postgres and yarn today. I had node before.

**Comment by nguyenvukhang** [comment]
After installing `postgresql` using homebrew, it isn't started by default.
To start it, run `brew services start postgresql`.

For a complete guide to start from scratch, refer to [this page in the docs](https://modtree-docs.vercel.app/docs/developer-guide/build-prerequisites)
